#define TAPPING_TERM    200
#define QUICK_TAP_TERM  175
#define FLOW_TAP_TERM   150
#define COMBO_TERM      30
#define ONESHOT_TIMEOUT 900

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define CHORDAL_HOLD