#pragma once

#define PERMISSIVE_HOLD
#define TAPPING_TERM 200
#define QUICK_TAP_TERM 150
#define COMBO_TERM 20
#define CAPS_WORD_IDLE_TIMEOUT 3000
#define ONESHOT_TIMEOUT 900
#define COMBO_MUST_TAP_PER_COMBO