#pragma once

#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define AUTO_SHIFT_TIMEOUT 160
#define AUTO_SHIFT_TIMEOUT_PER_KEY
// #define NO_AUTO_SHIFT_TAB

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define CAPS_WORD_IDLE_TIMEOUT 3000